#!/usr/bin/env bash
# Install nginx web server and GET request a string Holberton School
apt-get update
apt-get install -y nginx
service nginx start
echo "Holberton School" > /var/www/html/index.html
service nginx restart
