#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on web-01 server
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "42i $STRING" /etc/nginx/sites-available/default
    service nginx restart
fi
