#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on web-01 server
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
STRING="\\\n\terror_page 404 /custom_404.html;\n"
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "40i $STRING" /etc/nginx/sites-available/default
    service nginx restart
fi
